"""empty message

Revision ID: 5f0a59c3523e
Revises: 
Create Date: 2021-01-07 02:57:41.285441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f0a59c3523e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Message',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('UserName', sa.String(length=64), nullable=True),
    sa.Column('Messages', sa.Text(), nullable=True),
    sa.Column('CreateDate', sa.DateTime(), nullable=True),
    sa.Column('RoomId', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('Room',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Title', sa.String(length=64), nullable=True),
    sa.Column('URL', sa.String(length=64), nullable=True),
    sa.Column('UserID', sa.String(length=64), nullable=True),
    sa.Column('RoomID', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('UserAccounts',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('UserName', sa.String(length=64), nullable=True),
    sa.Column('Password', sa.String(length=64), nullable=True),
    sa.Column('MugShot', sa.String(length=64), nullable=True),
    sa.Column('CreateDate', sa.DateTime(), nullable=True),
    sa.Column('ModifiedDate', sa.DateTime(), nullable=True),
    sa.Column('Role', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('UserName')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UserAccounts')
    op.drop_table('Room')
    op.drop_table('Message')
    # ### end Alembic commands ###
