"""empty message

Revision ID: 8c936e4c8ee2
Revises: None
Create Date: 2020-12-30 01:44:55.621970

"""

# revision identifiers, used by Alembic.
revision = '8c936e4c8ee2'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Message',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('UserName', sa.String(length=64), nullable=True),
    sa.Column('Messages', sa.Text(), nullable=True),
    sa.Column('CreateDate', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('UserAccounts',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('UserName', sa.String(length=64), nullable=True),
    sa.Column('Password', sa.String(length=64), nullable=True),
    sa.Column('MugShot', sa.String(length=64), nullable=True),
    sa.Column('CreateDate', sa.DateTime(), nullable=True),
    sa.Column('ModifiedDate', sa.DateTime(), nullable=True),
    sa.Column('Role', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('UserName')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UserAccounts')
    op.drop_table('Message')
    ### end Alembic commands ###
